# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voxa/speech/v1/asr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voxa/speech/v1/asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from voxa.speech.v1 import audio_pb2 as voxa_dot_speech_dot_v1_dot_audio__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18voxa/speech/v1/asr.proto\x12\x0evoxa.speech.v1\x1a\x1avoxa/speech/v1/audio.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n\x19StreamingRecognizeRequest\x12)\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x1a.voxa.speech.v1.AudioFrame\x12\x34\n\x10\x66irst_frame_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"<\n\x1aStreamingRecognizeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\"t\n\x10RecognizeRequest\x12*\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x1a.voxa.speech.v1.AudioFrame\x12\x34\n\x10\x66irst_frame_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"N\n\x11RecognizeResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12%\n\x06tokens\x18\x02 \x03(\x0b\x32\x15.voxa.speech.v1.Token\"\'\n\x05Token\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x32\xc8\x01\n\x03\x41SR\x12o\n\x12StreamingRecognize\x12).voxa.speech.v1.StreamingRecognizeRequest\x1a*.voxa.speech.v1.StreamingRecognizeResponse(\x01\x30\x01\x12P\n\tRecognize\x12 .voxa.speech.v1.RecognizeRequest\x1a!.voxa.speech.v1.RecognizeResponseB:Z8github.com/jmarc101/voxa/api/gen/voxa/speech/v1;speechv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voxa.speech.v1.asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/jmarc101/voxa/api/gen/voxa/speech/v1;speechv1'
  _globals['_STREAMINGRECOGNIZEREQUEST']._serialized_start=105
  _globals['_STREAMINGRECOGNIZEREQUEST']._serialized_end=229
  _globals['_STREAMINGRECOGNIZERESPONSE']._serialized_start=231
  _globals['_STREAMINGRECOGNIZERESPONSE']._serialized_end=291
  _globals['_RECOGNIZEREQUEST']._serialized_start=293
  _globals['_RECOGNIZEREQUEST']._serialized_end=409
  _globals['_RECOGNIZERESPONSE']._serialized_start=411
  _globals['_RECOGNIZERESPONSE']._serialized_end=489
  _globals['_TOKEN']._serialized_start=491
  _globals['_TOKEN']._serialized_end=530
  _globals['_ASR']._serialized_start=533
  _globals['_ASR']._serialized_end=733
# @@protoc_insertion_point(module_scope)
