# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voxa/speech/v1/audio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voxa/speech/v1/audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avoxa/speech/v1/audio.proto\x12\x0evoxa.speech.v1\"Y\n\nAudioFrame\x12+\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x1b.voxa.speech.v1.AudioFormat\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08sequence\x18\x03 \x01(\x03*Z\n\x0b\x41udioFormat\x12\x1c\n\x18\x41UDIO_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41UDIO_FORMAT_PCM16\x10\x01\x12\x15\n\x11\x41UDIO_FORMAT_OPUS\x10\x02\x42:Z8github.com/jmarc101/voxa/api/gen/voxa/speech/v1;speechv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voxa.speech.v1.audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/jmarc101/voxa/api/gen/voxa/speech/v1;speechv1'
  _globals['_AUDIOFORMAT']._serialized_start=137
  _globals['_AUDIOFORMAT']._serialized_end=227
  _globals['_AUDIOFRAME']._serialized_start=46
  _globals['_AUDIOFRAME']._serialized_end=135
# @@protoc_insertion_point(module_scope)
